Repository iotaledger/iota-wiki, pull requests merged in 2021-08, with the labels that each got.

#85 Update tangle-explorer.md
  docs/use/utilities/tangle-explorer.md
Labels: documentation, feature

#84 Update iota-ipfs.md
  docs/use/utilities/iota-ipfs.md
Labels: documentation, feature

#92 Create about-nodes.md
  docs/participate/support-the-network/about-nodes.md
Labels: documentation, feature

#93 Create-Become-a-node-operator.md
  docs/participate/support-the-network/become-a-node-operator.md
Labels: documentation, feature

#96 Create messages.md
  docs/learn/about-iota/messages.md
Labels: documentation, feature

#94 Create node-software.md
  docs/participate/support-the-network/node-software.md
Labels: documentation, feature

#89 Update value-transfer.md
  docs/learn/about-iota/value-transfer.md
Labels: documentation, feature

#90 Update an-introduction-to-iota.md
  docs/learn/about-iota/an-introduction-to-iota.md
Labels: documentation, feature

#113 Add static location for pics, change all linked pics in Firefly Wallet.md
  docs/learn/about-iota/an-introduction-to-iota.md
  docs/learn/wallets/firefly-wallet.md
  static/img/learn/blockchain-bottleneck.gif
  static/img/learn/firefly/account_detail_customize.png
  static/img/learn/firefly/add_a_wallet.png
  static/img/learn/firefly/choose_send_from_wallet_ledger.png
  static/img/learn/firefly/confirm_receive_address_ledger.png
  static/img/learn/firefly/confirm_remainder_address_ledger.png
  static/img/learn/firefly/confirm_transaction_ledger.png
  static/img/learn/firefly/connect_ledger.png
  static/img/learn/firefly/create_a_wallet_ledger.png
  static/img/learn/firefly/dashboard.png
  static/img/learn/firefly/dispaly_amount_ledger.png
  static/img/learn/firefly/display_accept_ledger.png
  static/img/learn/firefly/display_ledger_address.png
  static/img/learn/firefly/generate_address_ledger.png
  static/img/learn/firefly/ledger_multiple_profile_view.png
  static/img/learn/firefly/multiple_wallet_view_ledger.png
  static/img/learn/firefly/okay_ledger_display.png
  static/img/learn/firefly/profile_start.png
  static/img/learn/firefly/receive_funds.png
  static/img/learn/firefly/receive_funds_wallet_choice.png
  static/img/learn/firefly/send_funds.png
  static/img/learn/firefly/send_payment_ledger.png
  static/img/learn/firefly/set_pin_ledger.png
  static/img/learn/firefly/setup_a_wallet_ledger.png
  static/img/learn/firefly/setup_complete_ledger.png
  static/img/learn/firefly/transaction_details_view.png
  static/img/learn/firefly/wallet_detail_view.png
  static/img/learn/firefly/wallet_view_ledger.png
  static/img/learn/milestones.gif
  static/img/learn/tangle-bottleneck.gif
Labels: documentation, feature

#61 Implement an in-page editor
  docusaurus.config.js
  package.json
  src/theme/EditThisPage/index.js
  yarn.lock
Labels: help wanted, feature

#129 Edit docs/learn/about-iota/roadmap-to-decentralization.md
  docs/learn/about-iota/roadmap-to-decentralization.md
Labels: documentation, feature

#128 Edit docs/learn/iota-token/buying-iota.md
  docs/learn/iota-token/buying-iota.md
Labels: documentation, feature

#134 Update and rename guide.md to exchange-integration-guide.md
  docs/develop/exchange-integration/exchange-integration-guide.md
  docs/develop/exchange-integration/guide.md
  sidebars.js
Labels: documentation, feature

#137 Update and rename papers.md to research-papers.md
  docs/learn/research/papers.md
  docs/learn/research/research-papers.md
  sidebars.js
Labels: documentation, feature

#132 Rework data-transfer.md
  docs/learn/about-iota/data-transfer.md
Labels: enhancement

#133 Rework an-introduction-to-iota.md
  docs/learn/about-iota/an-introduction-to-iota.md
Labels: enhancement

#136 Update research-outline.md
  docs/learn/research/research-outline.md
Labels: documentation, feature

#138 Update become-a-node-operator.md
  docs/participate/support-the-network/become-a-node-operator.md
Labels: documentation, enhancement, feature

#156 Edit docs/participate/support-the-network/become-a-node-operator.md
  docs/participate/support-the-network/become-a-node-operator.md
Labels: enhancement

#148 Edit docs/learn/about-iota/messages.md
  docs/learn/about-iota/messages.md
Labels: enhancement

#157 Update node-software.md
  docs/participate/support-the-network/node-software.md
Labels: enhancement
